apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: daily-journal
    patch: |
      - op: replace
        path: /metadata/namespace
        value: myapp-qa
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: ServiceAccount
      name: daily-journal
    patch: |
      - op: replace
        path: /metadata/namespace
        value: myapp-qa
  - target:
      kind: ConfigMap
      name: app-config
    patch: |
      - op: replace
        path: /metadata/namespace
        value: myapp-qa
  - target:
      kind: Service
      name: daily-journal
    patch: |
      - op: replace
        path: /metadata/namespace
        value: myapp-qa
  - target:
      kind: Ingress
      name: daily-journal
    patch: |
      - op: replace
        path: /metadata/namespace
        value: myapp-qa
  - target:
      kind: NetworkPolicy
      name: daily-journal-netpol
    patch: |
      - op: replace
        path: /metadata/namespace
        value: myapp-qa
